version: "3"

services:
  kafkaproducer1:
    container_name: kafkaproducer1
    image: kafkaproducer:latest
    restart: always
    environment:
      - TZ=Europe/Berlin
    ports:
      - 8000:8080
    depends_on:
      - zookeeper
  kafkaproducer2:
    container_name: kafkaproducer2
    image: kafkaproducer:latest
    restart: always
    environment:
      - TZ=Europe/Berlin
    ports:
      - 8001:8080
    depends_on:
      - zookeeper
  kafkaproducer3:
    container_name: kafkaproducer3
    image: kafkaproducer:latest
    restart: always
    environment:
      - TZ=Europe/Berlin
    ports:
      - 8002:8080
    depends_on:
      - zookeeper
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    container_name: kafka1
    image: 'bitnami/kafka:latest'
    ports:
      - 29091:29091
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29091
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29091
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - 'kafka1_data:/bitnami'
    depends_on:
      - zookeeper
  kafka2:
    container_name: kafka2
    image: 'bitnami/kafka:latest'
    ports:
      - 29092:29092
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - 'kafka2_data:/bitnami'
    depends_on:
      - zookeeper
  kafka3:
    container_name: kafka3
    image: 'bitnami/kafka:latest'
    ports:
      - 29093:29093
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092,PLAINTEXT_HOST://localhost:29093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - 'kafka3_data:/bitnami'
    depends_on:
      - zookeeper
  portainer:
    image: portainer/portainer
    restart: always
    command: -H unix:///var/run/docker.sock --admin-password '$$2y$$05$$aj6Y0ALq8FQaHmbbeZAUfe0/O.HAV5lly.4m9hwoaCtVERdHbIiTC'
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
#  kafka1_data:
#    driver: local
#  kafka2_data:
#    driver: local
#  kafka3_data:
#    driver: local
#  portainer_data:
#    driver: local
